### ISSUE TITLE
Coll dataset

### ISSUE THREAD

**Issue by Borisnaz** [TUM-DAML/gemnet_pytorch#1]
Hi,

Thanks for sharing this GemNet implementation.
Where can I download coll dataset in npz format? Or how it can be created?

Thanks,
Boris

**Comment by gasteigerjo** [comment]
We published the COLL dataset in xyz-format [here](https://figshare.com/articles/dataset/COLL_Dataset_v1_2/13289165/1). xyz is a standard, human-readable format. It should be rather straightforward to convert it to npz.

I'll probably upload an npz-version there as well soon.

**Comment by gasteigerjo** [comment]
I've now added the COLL npz-files to this repository.
