### ISSUE TITLE
the dihedral angle difinition

### ISSUE THREAD

**Issue by wang1215789** [TUM-DAML/gemnet_pytorch#11]
GemNet is a great work for molecules representation learning.I have a question about dihedral angle "cabd" definition,the definition in your paper seems not consider the direction of  dihedral  angle , what i means is that the  dihedral angles in the flowing picture is the same in your definition, but we konw the dihedral angles is different .The difference may have a influence on message passing and your model.
![image](https://user-images.githubusercontent.com/114713139/193175209-cfdd2be0-5522-4dc3-a5a7-603298d477bf.png)

**Comment by gasteigerjo** [comment]
Yes. We've experimented with versions of the dihedral angle that consider the directionality/handedness of the angle, but we found that it doesn't impact model performance. So we opted for the simpler variant.
