### ISSUE TITLE
The code that predicts on the test set? 

### ISSUE THREAD

**Issue by Xuxuduoyu** [TUM-DAML/gemnet_pytorch#15]
The predict.py file you submitted is about predictions for a molecule, can you upload the code that predicts on the test set? I would be very grateful.

**Comment by gasteigerjo** [comment]
The code [here](https://github.com/TUM-DAML/gemnet_pytorch/blob/master/train_seml.py#L346-L381) shows how to run evaluation.

To run this on the test set, you just have to swap the validation dataset to the test dataset, by loading it with code like [this](https://github.com/TUM-DAML/gemnet_pytorch/blob/master/train_seml.py#L216-L233). The only thing you need to change is the path passed via `val_dataset`.

Please beware if you run that file as-is and only change the path, you would do early stopping on the test set. That would be bad. You really should train the model without knowledge of the test set and then evaluate on test with code like the above.
