### ISSUE TITLE
QM9 dataset

### ISSUE THREAD

**Issue by smiles724** [TUM-DAML/gemnet_pytorch#3]
Hi, I notice you implemented experiments in extensive datasets. However, most of your baseline models show their performance in the popular QM9 dataset. Can you please provide this sort of information so that we can have a more clear understanding of how well your model is? Thanks.

**Comment by gasteigerjo** [comment]
GemNet focuses on molecular dynamics and force predictions, not on other molecular properties. QM9 only contains equilibrium configurations, on which force predictions wouldn't make any sense (all forces are 0).

But please do feel free to run tests. The project structure is rather similar to DimeNet's code, so you could use some stuff from the data container there. I wouldn't expect any substantial improvements out of the box. But with some hyperparameter tuning you might achieve something.
