### ISSUE TITLE
Reproducing Questions

### ISSUE THREAD

**Issue by chao1224** [TUM-DAML/gemnet_pytorch#8]
Hi there,

Thank you for providing the codebase. I am trying to reproduce GemNet on COLL and MD17, and have two questions below:

1. For COLL, I'm wondering what is the total training time? On my end, it seems to be quite large (300-400 hours), so just want to double-check with you.
2. For MD17, can you help provide the `config.yml` and `scaling_factors.json` files on each task?

Any help is appreciated.

**Comment by gasteigerjo** [comment]
Your training time indeed seems a bit long, even for GemNet-Q.
![grafik](https://user-images.githubusercontent.com/9202783/154946668-cf46386d-2edf-4565-9dd2-4992cbbab859.png)

You can find everything you need to change in `config.yml` in Appendix G of the paper. You can compute the scaling factors using `fit_scaling.py`.
